platform-coop-toolkit/pinecone

src/assets/scripts/Pinecone/index.js, src/assets/styles/components/_menu--home.scss, src/assets/styles/components/_menu.scss, src/assets/styles/layouts/_header.scss, src/components/02-molecules/00-menu/menu.config.js
Currently a submenu in the main navigation can be dismissed by tabbing out of it or by clicking anywhere else on the page. This PR allows it to be dismissed with the `escape` key as well.
1. Toggle the submenu at https://deploy-preview-79--pinecone.netlify.com/components/preview/menu--default.html
2. Press the `escape` key.
**Expected behavior:** Submenu is dismissed.
=> Allow dismissal of submenu with escape key

src/assets/styles/components/_badges.scss
Increase badge text contrast.
Review component: http://deploy-preview-84--pinecone.netlify.com/components/preview/badges.html
- Fixes #80.
=> Improve contrast (fixes #80)

src/assets/styles/layouts/_archive.scss, src/components/03-layouts/02-archive/archive.config.js, src/components/03-layouts/02-archive/archive.njk
When no filters are applied, the margin between filter/sort and the resource list on the browse page needed to be reduced.
Review component:
- https://deploy-preview-137--pinecone.netlify.com/components/preview/archive--unfiltered.html
=> fix: adjust top margin for unfiltered resource list

src/assets/styles/components/_menu--home.scss, src/assets/styles/components/_menu.scss
Resolves ambiguity in menu states (#98).
Review components:
- https://deploy-preview-145--pinecone.netlify.com/components/preview/menu--default.html
- https://deploy-preview-145--pinecone.netlify.com/components/preview/menu--home.html
- Resolves #98.
=> fix: improve current/active/focus menu states (resolves #98)

src/assets/styles/layouts/_archive.scss, src/assets/styles/layouts/_header.scss, src/assets/styles/layouts/_page.scss
The home page banner (header area including logo and navigation) has a blue background colour. I applied it using the `.home` class. However, the home page in WordPress has both `.home` and `.page` classes, so this rule was being overridden by the banner colour style for pages. This PR addresses this issue.
Review menu and home menu components and confirm that the banner areas have the correct background colours:
- https://deploy-preview-146--pinecone.netlify.com/components/preview/menu--default.html
- https://deploy-preview-146--pinecone.netlify.com/components/preview/menu--home.html
=> fix: resolve specificity issue with banner background color

src/assets/styles/components/_menu.scss, src/components/01-atoms/_svg/_svg.njk
This PR aligns the default class names for SVG icons with [BEM syntax](http://getbem.com/naming/). Each icon has a default class of `.icon`, and a modifier class of `.icon--<icon>` (e.g. `.icon--close`).
Verify that icon and menu components still display correct icons:
- https://deploy-preview-147--pinecone.netlify.com/components/preview/icons.html
- https://deploy-preview-147--pinecone.netlify.com/components/preview/menu--default.html
=> fix: make icon class names consistent with BEM syntax

src/assets/styles/components/_menu--home.scss, src/assets/styles/components/_menu.scss, src/components/01-atoms/_svg/_svg.config.js, src/components/01-atoms/_svg/_svg.njk, src/components/02-molecules/00-menu/menu.config.js, src/components/02-molecules/00-menu/menu.njk
Adds language menu.
Review component in context:
- https://deploy-preview-148--pinecone.netlify.com/components/preview/menu--default.html
- https://deploy-preview-148--pinecone.netlify.com/components/preview/menu--home.html
**Expected behavior:** 
- Resolves #67.
=> feat: add language menu (resolves #67)

.github/workflows/publish-package.yml
See: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/publishing-nodejs-packages#publishing-packages-to-github-packages
Publish a release, see what happens!
=> feat: add automatic publishing to GitHub Package Registry

src/assets/styles/components/_accordion.scss, src/assets/styles/components/_disclosure-button.scss, src/assets/styles/components/_menu.scss
Speeds up animation for dropdown menu, accordion, and disclosure button icons to 0.3s.
Review components:
- https://deploy-preview-158--pinecone.netlify.com/components/preview/menu--default.html
- https://deploy-preview-158--pinecone.netlify.com/components/preview/accordion--default.html
- https://deploy-preview-158--pinecone.netlify.com/components/preview/disclosure-button.html
=> fix: speed up disclosure icon animations

src/assets/styles/components/_buttons.scss, src/assets/styles/components/_forms.scss, src/assets/styles/components/_links.scss, src/components/01-atoms/04-link/link.config.js, src/components/01-atoms/04-link/link.njk, src/components/01-atoms/06-call-to-action/call-to-action.config.js
Adds variants of links and calls to action for dark backgrounds. Prerequisite for home page (#161).
Review components:
- https://deploy-preview-165--pinecone.netlify.com/components/preview/link--default-inverse.html
- https://deploy-preview-165--pinecone.netlify.com/components/preview/call-to-action--default-inverse.html
- Blocker for #161.
- Resolves #163.
=> feat: add inverse link and CTA variants

src/assets/styles/layouts/_home.scss, src/components/03-layouts/04-home/home.njk
Adds customize link to the home feed.
Review home page layout: https://deploy-preview-191--pinecone.netlify.com/components/preview/home.html.
**Expected behavior:** Link appears to the right of section title and moves below the title if the link text is too long to fit.
Implemented using flexbox with `flex-wrap: wrap` to allow overflow to second line. This necessitated placing the section heading and the link in a container element. I used a `<header>` since we're within a named `<section>`; not sure if this adds unnecessary semantics for screen readers. Thoughts, @jhung?
- Fixes #171.
=> feat: add customize link to homepage feed (fixes #171)

src/assets/scripts/Pinecone/NestedCheckbox/index.js
This PR restores click functionality to the parent checkbox of nested checkboxes in the filter list.
1. View the Archive component: https://deploy-preview-212--pinecone.netlify.com/components/preview/archive
2. Expand "Goals" in the filter list.
3. Check and uncheck one of the parent checkboxes (e.g. 'Build a co-op').
**Expected behavior:** The parent checkboxe's state changes, and children are checked or unchecked as appropriate.
- Resolves #210.
=> fix: restore functionality to nested checkboxes (resolves #210)

README.md
* [ x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [ x] This isn't a duplicate of an existing pull request
Adds the minimal number of steps needed to pull Pinecone js and css into a Django project.
1. I've run through the listed commands to verify.
**Expected behavior:** Pinecone styles and JavaScript should be available to the Django project.
N/A
N/A
=> docs: add minimal steps for incorporating Pinecone into a Django project

src/assets/styles/common/_global.scss, src/assets/styles/components/_button.scss, src/assets/styles/components/_notification.scss, src/assets/styles/layouts/_favorites.scss, src/assets/styles/pinecone.scss, src/components/01-atoms/09-button/button.config.js, src/components/01-atoms/09-button/button.njk, src/components/02-molecules/01-card/card--resource.njk, src/components/02-molecules/01-card/card.config.js, src/components/03-layouts/05-favorites/favorites.config.js, src/components/03-layouts/05-favorites/favorites.njk
- Adds favorites page layout.
- Add align-right and align-left classes.
- Make notifications sticky (resolves #241).
- Add destructive borderless button variant (needs adjusted active and focus states, dependent on #240).
Review layout: https://deploy-preview-242--pinecone.netlify.com/components/preview/favorites.html
- Resolves #205.
- Resolves #241.
=> feat: add component and styling for favorites page

src/assets/scripts/Pinecone/MenuButton/index.js
Allow menu button to be closed by clicking elsewhere on the page.
Review menu button component.
- Resolves #232.
=> fix: allow menu button to be closed by clicking elsewhere (resolve #232)

src/assets/scripts/Pinecone/Dialog/index.js, src/assets/scripts/pinecone.js, src/assets/styles/components/_dialog.scss, src/assets/styles/components/_filter-sort.scss, src/assets/styles/layouts/_archive.scss, src/components/02-molecules/06-dialog/dialog.config.js, src/components/02-molecules/06-dialog/dialog.njk, src/components/03-layouts/02-archive/archive.njk, src/components/03-layouts/06-search-results/search-results.config.js, src/components/03-layouts/06-search-results/search-results.njk, src/components/_preview.njk
Review dialog component and search results layout.
- Resolves #207.
=> feat: add search results and dialog with input (resolves #207)

src/assets/styles/layouts/_home.scss, src/components/layouts/home/home.njk
Fixes #257 .
1. Go to Layouts > Home
2. Notice how byline is on a separate line from the title.
3. Edit `home.config.js` lines 63 and 64 to generate 1 word title and bylines (i.e. min: 1, max: 1).
4. Rebuild pinecone with this new configuration `npm run build`
5. Run `fractal start`
6. Go to Layouts > Home
7. Notice that bylines are still on separate lines even though the titles and bylines are short.
**Expected behavior:** 
The byline for a resource should be on its own line regardless of the length of the title or byline string.
Resolves #257 .
=> fix: resolve issue with byline appearing inline with resource title on home feed

src/assets/styles/components/_card.scss, src/assets/styles/layouts/_resource.scss, src/components/layouts/archive/archive.config.js, src/components/layouts/favorites/favorites.config.js, src/components/layouts/resource/resource.config.js, src/components/layouts/resource/resource.njk, src/components/layouts/search-results/search-results.config.js, src/components/molecules/card/card--resource.njk, src/components/molecules/card/card.config.js
Resolves #268.
1. Review resource card, archive, and single resource views.
**Expected behavior:** Subscription indicator appears.
- Resolves #268.
=> feat: add subscription indicator to resources (resolves #268)

package.json, src/docs/development/releasing.md, src/docs/usage/sage.md
Switches package publishing to NPM.
=> feat: switch to NPM, update docs

src/assets/styles/components/_image.scss, src/assets/styles/pinecone.scss, src/components/atoms/image/image.config.js, src/components/atoms/image/image.njk, src/components/molecules/card/card.config.js, src/components/molecules/card/card.njk
Adds a component for images, with three variants:
- Default (with `alt` tag)
- Decorative (with `role="presentation"` and empty `alt` tag)
- Missing Alt Text (with no `alt` tag, blurred 10px)
1. Review image components.
**Expected behavior:** Images behave as expected for sighted users and assistive technology users.
- See https://github.com/hankchizljaw/modern-css-reset/pull/22
- See https://github.com/jensimmons/cssremedy/blob/master/css/remedy.css#L56-L73
- See https://www.w3.org/WAI/tutorials/images/decorative/
- Resolves #230.
=> feat: add image atom, blur images with missing alt tags

src/assets/scripts/Pinecone/Dialog/index.js, src/assets/scripts/Pinecone/FilterList/index.js
The dialog component sets direct descendants of the body to `inert`, which interferes with [@wordpress/a11y](https://www.npmjs.com/package/@wordpress/a11y) and the `aria-live` containers it uses. This PR ensures that aria-live containers are not set to inert.
When invoking a dialog, direct descendants of the `body` tag with an `aria-live` attribute should not be set to `inert`.
- Related to https://github.com/platform-coop-toolkit/coop-library/issues/200.
=> fix: don't make aria-live containers inert

src/assets/styles/layouts/_resource.scss
Gives the date added field a bottom margin on single resource view (tablet and below).
1. Inspect single resource view on tablet/mobile.
**Expected behavior:** Date added has a bottom margin of 1.5rem.
- Resolves https://github.com/platform-coop-toolkit/coop-library/issues/247.
=> fix: date added margin

src/components/molecules/dialog/dialog.config.js
I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
Fixing typo in Dialog example.
=> fix: typo "your" to "you"

src/assets/styles/components/_input.scss, src/components/molecules/filter-list/filter-list.njk
Resolve an issue where invisible checkbox in filter-list was receiving keyboard focus. Also fixes an issue where filter-list checkbox IDs were not properly populated.
1. Go to filter-list
2. Use keyboard to expand and tab through list of filters
3. Focus should move from visible element to visible element in a predictable and expected way.
Fixes #317.
=> fix: filter list checkbox properly hidden and has proper IDs

src/assets/images/curriculum.svg, src/components/layouts/favorites/favorites.config.js, src/components/layouts/home/home.config.js
Resolves 404 errors for educational curriculum and academic paper icons on home layout.
1. Visit home layout.
**Expected behavior:** All resource card icons are properly displayed.
Props @erictheise for catching this.
=> fix: resolve 404 errors for icons

src/assets/styles/components/_input.scss, src/components/layouts/archive/archive.config.js
This fixes an issue where a top-level checkbox in the filter list would be overlapped by the disclosure button.
1. Review component: https://deploy-preview-347--pinecone.netlify.app/components/preview/archive--default
**Expected behavior:** Goals &rarr; Build a Platform or Protocol should wrap instead of being overlapped by the disclosure button as it is here: https://resources.platform.coop/resources/
Fixes #292.
=> fix: prevent top level checkbox overlap (fixes #292)

src/assets/styles/components/_input.scss, src/components/10-atoms/100-form-elements/50-radio-buttons/radio-buttons.njk, src/components/10-atoms/100-form-elements/_checkbox/_checkbox.njk
Uses `appearance: none` to remove default radio button and checkbox styles instead of relying on the label being adjacent to the element.
TODO:
1. Review checkbox, custom checkbox and radio button components.
**Expected behavior:** They match the current styling.
- Resolves #286.
- Resolves #342.
=> feat: use appearance to style radio buttons and checkboxes

src/assets/styles/components/_accordion.scss, src/assets/styles/components/_button.scss, src/assets/styles/components/_menu--home.scss, src/assets/styles/components/_menu-button.scss, src/assets/styles/components/_search.scss, src/assets/styles/layouts/_home.scss
- Fixes #363 - Search focus borders appear as different widths
- Fixes #364 - Search inverts when active. 
- Fixes #365 - Menu button inverted focus and active style
- Fixes #368 - Radio group selected state
- Fixes #401 - Accordion has bottom border when active
Search button:
1. Test active state of the search button on the following:
* Search button
* Search form
* Home Layout
2. Search focus/active borders should appear consistent on both the input field and search button (see #363). Note: existing issues with box shadow rendering on Firefox may cause outer and inner borders to appear different widths. See #360).
3. The search button should invert when active See #364 .
Menu button:
1. Test the focus and active state on the following:
* Menu button
* Page layout (mobile)
* Home layout …
=> Fixes and tweaks to state styles
